# src/api.py
import hmac
import hashlib
import secrets
import bcrypt
import jwt
import os
import logging as l
from pydantic import BaseModel
from fastapi import APIRouter, HTTPException, status, Header, Depends, Request, Response
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel, EmailStr, Field
from psycopg import Connection
from fun.database import get_db
from datetime import datetime, timedelta, timezone
from typing import Optional
from datetime import datetime


# JWT
SECRET_KEY = os.getenv("JWT_SECRET","WhiteWolf")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 1440  # 24h

# Initialize the router
godot_router = APIRouter(tags=["Godot Client API"])
dev_router = APIRouter(tags=["Developer Dashboard"])
security = HTTPBearer()

# --- Pydantic Validation Models ---
class DeveloperRegister(BaseModel):
    email: EmailStr
    password: str = Field(..., min_length=8, description="Password must be at least 8 characters long")

class GameCreate(BaseModel):
    game_name: str

class ScorePayload(BaseModel):
    player_name: Optional[str] = Field(
        default=None, 
        description="The player's nickname",
        examples=["PlayerOne"]
    )
    score: int = Field(
        description="The high score achieved by the player. Must be an intege.",
        examples=[2500]
    )
    hash: Optional[str] = Field(
        default=None, 
        description="A verification hash generated by the game client to prevent score tampering.",
        examples=["e99a18c428cb38d5f260853678922e03"]
    )

class ScoreEntry(BaseModel):
    player_name: str
    score: int
    timestamp: datetime

class ScoresResponse(BaseModel):
    scores: list[ScoreEntry]

class PlayerAuthPayload(BaseModel):
    username: str = Field(..., min_length=3, max_length=50)
    password: str = Field(..., min_length=6)


# --- 1. DEVELOPER JWT ---
def create_access_token(data: dict):
    to_encode = data.copy()
    expire = datetime.now(timezone.utc) + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode.update({"exp": expire})
    encoded_jwt = jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)
    return encoded_jwt

def get_current_user_id(credentials: HTTPAuthorizationCredentials = Depends(security)) -> int:
    token = credentials.credentials
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        user_id: str = payload.get("sub")
        if user_id is None:
            raise HTTPException(status_code=401, detail="Invalid token claims.")
        return int(user_id)
    except jwt.PyJWTError:
        raise HTTPException(status_code=401, detail="Could not validate credentials / Token expired.")

def create_access_token(data: dict):
    to_encode = data.copy()
    expire = datetime.now(timezone.utc) + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode.update({"exp": expire})
    encoded_jwt = jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)
    return encoded_jwt

# --- 2. PLAYERS JWT ---
def create_player_access_token(player_id: int, game_id: int, username: str):
    expire = datetime.now(timezone.utc) + timedelta(days=30)
    to_encode = {
        "sub": str(player_id),
        "game_id": game_id,
        "username": username,
        "role": "player",
        "exp": expire
    }
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)


# --- 3. DEVELOPER MANAGEMENT PANEL ---

@dev_router.post("/api/dev/register", status_code=status.HTTP_201_CREATED)
def register_developer(payload: DeveloperRegister, db: Connection = Depends(get_db)):
    hashed_password = bcrypt.hashpw(payload.password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
    
    with db.cursor() as cursor:
        try:
            cursor.execute(
                "INSERT INTO users (email, password_hash) VALUES (%s, %s) RETURNING id, email;",
                (payload.email, hashed_password)
            )
            user = cursor.fetchone()
            db.commit()
            return {"message": "Account created successfully", "user": user}
        except Exception:
            db.rollback()
            raise HTTPException(status_code=400, detail="Email already registered.")

@dev_router.post("/api/dev/games", status_code=status.HTTP_201_CREATED)
def create_game(payload: GameCreate, db: Connection = Depends(get_db),current_user_id: int = Depends(get_current_user_id)):
    l.info("i try to create game")
    api_key = f"ww_key_{secrets.token_hex(64)}"
    
    
    with db.cursor() as cursor:
        try:
            cursor.execute(
                "INSERT INTO games (user_id, game_name, api_key) VALUES (%s, %s, %s) RETURNING *;",
                (current_user_id, payload.game_name, api_key)
            )
            game = cursor.fetchone()
            db.commit()
            return {"message": "Game created successfully", "game": game}
        except Exception as e:
            db.rollback()
            l.error(f"Failed to create game workflow: {e}")
            raise HTTPException(status_code=500, detail="Failed to create game workflow.")


@dev_router.post("/api/dev/login")
def login_developer(payload: DeveloperRegister, db: Connection = Depends(get_db)):
    with db.cursor() as cursor:
        cursor.execute("SELECT id, email, password_hash FROM users WHERE email = %s;", (payload.email,))
        user = cursor.fetchone()
        
        if not user or not bcrypt.checkpw(payload.password.encode('utf-8'), user['password_hash'].encode('utf-8')):
            raise HTTPException(status_code=401, detail="Invalid email or password.")
            
        access_token = create_access_token(data={"sub": str(user['id'])})
        
        return {
            "access_token": access_token,
            "token_type": "bearer"
        }


@dev_router.get("/api/dev/games")
def get_developer_games(db: Connection = Depends(get_db), current_user_id: int = Depends(get_current_user_id)):
    with db.cursor() as cursor:
        cursor.execute("SELECT id, game_name, current_users, max_users FROM games WHERE user_id = %s;", (current_user_id,))
        games = cursor.fetchall()
        return {"games": games}


@dev_router.get("/api/dev/games/{game_id}/api_key")
def get_game_api(game_id: int,db: Connection = Depends(get_db), current_user_id: int = Depends(get_current_user_id)):
    try:
        with db.cursor() as cursor:
            cursor.execute(
                """
                SELECT id, game_name, api_key 
                FROM games 
                WHERE id = %s AND user_id = %s;
                """,
                (game_id, current_user_id)
            )
            game = cursor.fetchone()
            if not game:
                raise HTTPException(
                    status_code=status.HTTP_404_NOT_FOUND,
                    detail="Game not found or you do not have permission to view it."
                )
            # l.debug(f"api game return {game["api_key"]}")
            return {
                "id": game["id"],
                "game_name": game["game_name"],
                "api_key": game["api_key"]
            }
    except Exception as e:
        l.error(f"download game api error: {e}")
        raise HTTPException(status_code=500, detail="download game api error")

@dev_router.put("/api/dev/games/{game_id}/api_key_regenerate")
def regenerate_game_api(game_id: int,db: Connection = Depends(get_db), current_user_id: int = Depends(get_current_user_id)):
    try:
        new_api_key = f"ww_key_{secrets.token_hex(64)}"
        with db.cursor() as cursor:
            cursor.execute(
                """
                UPDATE games
                SET api_key=%s
                WHERE id = %s AND user_id = %s;
                """,
                (new_api_key, game_id, current_user_id)
            )
            if cursor.rowcount == 0:
                raise HTTPException(
                    status_code=status.HTTP_404_NOT_FOUND,
                    detail="Game not found or you do not have permission to view it"
                )
            db.commit()
            return Response(status_code=204)
    except HTTPException:
        raise
    except Exception as e:
        l.error(f"api regenerate error: {e}")
        raise HTTPException(status_code=500, detail="api regenerate error")

@dev_router.get("/api/{game_id}/scores",response_model=ScoresResponse)
def get_scores(game_id: int,db: Connection = Depends(get_db), current_user_id: int = Depends(get_current_user_id)):
    try:    
        with db.cursor() as cursor:
            cursor.execute(
                "SELECT id FROM games WHERE user_id = %s AND id = %s;", 
                (current_user_id, game_id)
            )
            game = cursor.fetchone()
            
            if not game:
                raise HTTPException(status_code=401, detail="Game not found or you do not have permission to view it")
                
            cursor.execute(
                """
                SELECT player_name, score, timestamp 
                FROM leaderboards 
                WHERE game_id = %s 
                ORDER BY score DESC 
                LIMIT 20;
                """,
                (game['id'],)
            )
                
            rows = cursor.fetchall()
            return {"scores": rows}
            
    except HTTPException:
        raise
    except Exception as e:
        l.error(f"get_scores endpoint error: {e}")
        raise HTTPException(status_code=500, detail="get_scores endpoint error")

# --- 4. GODOT ENDPOINTS ---

@godot_router.get("/api/godot/{game_id}/scores",response_model=ScoresResponse)
def get_scores(game_id: int, username: Optional[str] = None, x_api_key: str = Header(...), db: Connection = Depends(get_db)):
    try:    
        with db.cursor() as cursor:
            cursor.execute(
                "SELECT id FROM games WHERE api_key = %s AND id = %s;", 
                (x_api_key, game_id)
            )
            game = cursor.fetchone()
            
            if not game:
                raise HTTPException(status_code=401, detail="Invalid API Key or Game ID.")
                
            if username:
                cursor.execute(
                    """
                    SELECT player_name, score, timestamp 
                    FROM leaderboards 
                    WHERE game_id = %s AND player_name = %s 
                    ORDER BY score DESC 
                    LIMIT 20;
                    """,
                    (game['id'], username)
                )
            else:
                cursor.execute(
                    """
                    SELECT player_name, score, timestamp 
                    FROM leaderboards 
                    WHERE game_id = %s 
                    ORDER BY score DESC 
                    LIMIT 20;
                    """,
                    (game['id'],)
                )
                
            rows = cursor.fetchall()
            return {"scores": rows}
            
    except HTTPException:
        raise
    except Exception as e:
        l.error(f"get_scores endpoint error: {e}")
        raise HTTPException(status_code=500, detail="get_scores endpoint error")


@godot_router.post("/api/godot/scores", status_code=status.HTTP_201_CREATED)
def post_score(payload: ScorePayload, x_api_key: str = Header(...), db: Connection = Depends(get_db)):
    with db.cursor() as cursor:
        cursor.execute("SELECT id, api_secret FROM games WHERE api_key = %s;", (x_api_key,))
        game = cursor.fetchone()
        
        if not game:
            raise HTTPException(status_code=401, detail="Invalid API Key.")
            
        raw_string = f"{payload.player_name}:{payload.score}:"
        server_hash = hashlib.sha256(raw_string.encode('utf-8') + game['api_secret'].encode('utf-8')).hexdigest()
        
        if not hmac.compare_digest(server_hash, payload.hash):
            raise HTTPException(status_code=403, detail="Score verification failed. Cheating detected!")
            
        try:
            cursor.execute(
                "INSERT INTO leaderboards (game_id, player_name, score) VALUES (%s, %s, %s);",
                (game['id'], payload.player_name, payload.score)
            )
            db.commit()
        except Exception:
            db.rollback()
            raise HTTPException(status_code=500, detail="Database submission error.")
            
        return {"message": "Score saved successfully!"}


@godot_router.post("/api/godot/{game_id}/players/register", status_code=status.HTTP_201_CREATED)
def register_game_player(game_id: int, payload: PlayerAuthPayload, x_api_key: str = Header(...), db: Connection = Depends(get_db)):
    """
    Register player from godot game
    """
    try:
        with db.cursor() as cursor:
            # 1. API key verification
            cursor.execute("SELECT id FROM games WHERE api_key = %s AND id = %s;", (x_api_key, game_id))
            game = cursor.fetchone()
            if not game:
                raise HTTPException(status_code=401, detail="Invalid API Key or Game ID.")
                
            hashed_password = bcrypt.hashpw(payload.password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
            
            try:
                cursor.execute(
                    """
                    INSERT INTO players (game_id, username, password_hash) 
                    VALUES (%s, %s, %s) 
                    RETURNING id, username;
                    """,
                    (game_id, payload.username, hashed_password)
                )
                new_player = cursor.fetchone()
                db.commit()
                return {"message": "Player registered successfully", "username": new_player["username"]}
                
            except Exception:
                db.rollback()
                raise HTTPException(status_code=400, detail="Username is already taken in this game.")
    except HTTPException:
        raise
    except Exception as e:
        db.rollback()
        l.error(f"create user error {e}")
        raise HTTPException(status_code=500, detail="Create user error")


@godot_router.post("/api/godot/{game_id}/players/login")
def login_game_player(game_id: int, payload: PlayerAuthPayload, x_api_key: str = Header(...), db: Connection = Depends(get_db)):
    """
    Player login from within the game. Returns a JWT token.
    """
    try:
        with db.cursor() as cursor:
            # Api key verification
            cursor.execute("SELECT id FROM games WHERE api_key = %s AND id = %s;", (x_api_key, game_id))
            game = cursor.fetchone()
            if not game:
                raise HTTPException(status_code=401, detail="Invalid API Key or Game ID.")
                
            # Download player for specific game
            cursor.execute(
                "SELECT id, username, password_hash FROM players WHERE game_id = %s AND username = %s;",
                (game_id, payload.username)
            )
            player = cursor.fetchone()
            
            # Password check
            if not player or not bcrypt.checkpw(payload.password.encode('utf-8'), player['password_hash'].encode('utf-8')):
                raise HTTPException(status_code=401, detail="Invalid username or password.")
                
            # JWT generate
            player_token = create_player_access_token(
                player_id=player['id'], 
                game_id=game_id, 
                username=player['username']
            )

            # Update last login in db
            cursor.execute(
                """
                UPDATE players
                SET last_login=%s
                WHERE game_id = %s AND username = %s;
                """,
                (datetime.now(),game_id, payload.username)
            )

            db.commit()

            return {
                "player_token": player_token,
                "username": player['username'],
                "token_type": "bearer"
            }
    except HTTPException:
        raise
    except Exception as e:
        db.rollback()
        l.error(f"login user error {e}")
        raise HTTPException(status_code=500, detail="Login user error")