# src/api_godot.py
import hmac
import hashlib
import secrets
import bcrypt
import jwt
import os
import logging as l
from pydantic import BaseModel
from fastapi import APIRouter, HTTPException, status, Header, Depends, Request, Response
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel, EmailStr, Field
from psycopg import Connection
from fun.database import get_db
from datetime import datetime, timedelta, timezone
from typing import Optional
from datetime import datetime
from fun.limiter import limiter

godot_router = APIRouter(tags=["Godot Client API"])

SECRET_KEY_PLAYER = os.getenv("JWT_SECRET","WhiteWolf_Player")
ALGORITHM = "HS256"


# --- Pydantic Validation Models ---
class ScorePayload(BaseModel):
    player_name: Optional[str] = Field(
        default=None, 
        description="The player's nickname",
        examples=["PlayerOne"]
    )
    score: int = Field(
        description="The high score achieved by the player. Must be an intege.",
        examples=[2500]
    )
    hash: Optional[str] = Field(
        default=None, 
        description="A verification hash generated by the game client to prevent score tampering.",
        examples=["e99a18c428cb38d5f260853678922e03"]
    )

class ScoreEntry(BaseModel):
    player_name: str
    score: int
    timestamp: datetime

class ScoresResponse(BaseModel):
    scores: list[ScoreEntry]

class UserEntry(BaseModel):
    username: str
    last_login: Optional[datetime] = None
    created_at: datetime

class UserResponse(BaseModel):
    users: list[UserEntry]

class PlayerAuthPayload(BaseModel):
    username: str = Field(..., min_length=3, max_length=50)
    password: str = Field(..., min_length=6)


# --- 2. PLAYERS JWT ---
def create_player_access_token(player_id: int, game_id: int, username: str):
    expire = datetime.now(timezone.utc) + timedelta(days=3)
    to_encode = {
        "sub": str(player_id),
        "game_id": game_id,
        "username": username,
        "role": "player",
        "exp": expire
    }
    return jwt.encode(to_encode, SECRET_KEY_PLAYER, algorithm=ALGORITHM)

# --- GODOT ENDPOINTS ---

@godot_router.get("/api/godot/{game_id}/scores",response_model=ScoresResponse)
@limiter.limit("15/minute")
def get_scores(request: Request, game_id: int, username: Optional[str] = None, x_api_key: str = Header(...), db: Connection = Depends(get_db)):
    try:    
        with db.cursor() as cursor:
            cursor.execute(
                "SELECT id FROM games WHERE api_key = %s AND id = %s;", 
                (x_api_key, game_id)
            )
            game = cursor.fetchone()
            
            if not game:
                raise HTTPException(status_code=401, detail="Invalid API Key or Game ID.")
                
            if username:
                cursor.execute(
                    """
                    SELECT player_name, score, timestamp 
                    FROM leaderboards 
                    WHERE game_id = %s AND player_name = %s 
                    ORDER BY score DESC 
                    LIMIT 20;
                    """,
                    (game['id'], username)
                )
            else:
                cursor.execute(
                    """
                    SELECT player_name, score, timestamp 
                    FROM leaderboards 
                    WHERE game_id = %s 
                    ORDER BY score DESC 
                    LIMIT 20;
                    """,
                    (game['id'],)
                )
                
            rows = cursor.fetchall()
            return {"scores": rows}
            
    except HTTPException:
        raise
    except Exception as e:
        l.error(f"get_scores endpoint error: {e}")
        raise HTTPException(status_code=500, detail="get_scores endpoint error")


@godot_router.post("/api/godot/{game_id}/scores", status_code=status.HTTP_201_CREATED)
@limiter.limit("10/minute")
def post_score(request: Request, game_id: int, payload: ScorePayload, x_api_key: str = Header(...), db: Connection = Depends(get_db)):
    with db.cursor() as cursor:
        cursor.execute("SELECT id, api_secret FROM games WHERE api_key = %s;", (x_api_key,))
        game = cursor.fetchone()
        
        if not game:
            raise HTTPException(status_code=401, detail="Invalid API Key.")
            
        l.debug(f"post score game: {game}")
        
        raw_string = f"{payload.player_name}:{payload.score}:"
        server_hash = hashlib.sha256(raw_string.encode('utf-8') + game['api_secret'].encode('utf-8')).hexdigest()
        
        if not hmac.compare_digest(server_hash, payload.hash):
            raise HTTPException(status_code=403, detail="Score verification failed. Cheating detected!")
            
        try:
            # check if player exist:
            cursor.execute(
                "SELECT score FROM leaderboards WHERE game_id = %s AND player_name = %s;",
                (game_id, payload.player_name)
            )
            existing_score = cursor.fetchone()

            if existing_score:
                cursor.execute(
                    "UPDATE leaderboards SET score = %s WHERE game_id = %s AND player_name = %s;",
                    (payload.score, game_id, payload.player_name)
                )
            else:
                cursor.execute(
                    "INSERT INTO leaderboards (game_id, player_name, score) VALUES (%s, %s, %s);",
                    (game_id, payload.player_name, payload.score)
                )
                
            db.commit()
        except Exception as e:
            db.rollback()
            l.error(f"Database error: {e}")
            raise HTTPException(status_code=500, detail="Database submission error.")
            
        return {"message": "Score saved successfully!"}


@godot_router.post("/api/godot/{game_id}/players/register", status_code=status.HTTP_201_CREATED)
@limiter.limit("5/minute")
def register_game_player(request: Request, game_id: int, payload: PlayerAuthPayload, x_api_key: str = Header(...), db: Connection = Depends(get_db)):
    """
    Register player from godot game
    """
    try:
        with db.cursor() as cursor:
            # API key verification and fetch game limits
            cursor.execute(
                "SELECT id, current_users, max_users FROM games WHERE api_key = %s AND id = %s;",
                (x_api_key, game_id)
            )
            game = cursor.fetchone()
            if not game:
                raise HTTPException(status_code=401, detail="Invalid API Key or Game ID.")
            
            # Check player limit
            if game["current_users"] >= game["max_users"]:
                raise HTTPException(status_code=403, detail="Max player number reached for this game")

            # Check if username already taken
            cursor.execute(
                "SELECT id FROM players WHERE game_id = %s AND username = %s;",
                (game_id, payload.username)
            )
            if cursor.fetchone():
                raise HTTPException(status_code=409, detail="Username already taken in this game.")

            # Hash password
            hashed_password = bcrypt.hashpw(
                payload.password.encode('utf-8'), 
                bcrypt.gensalt()
            ).decode('utf-8')
            
            # Insert player
            cursor.execute(
                """
                INSERT INTO players (game_id, username, password_hash) 
                VALUES (%s, %s, %s) 
                RETURNING id, username;
                """,
                (game_id, payload.username, hashed_password)
            )
            new_player = cursor.fetchone()
            
            # Increment player count atomically
            cursor.execute(
                "UPDATE games SET current_users = current_users + 1 WHERE id = %s;",
                (game_id,)
            )
            
            db.commit()
            
            return {
                "message": "Player registered successfully", 
                "username": new_player["username"]
            }
            
    except HTTPException:
        raise
    except Exception as e:
        db.rollback()
        l.error(f"create user error {e}")
        raise HTTPException(status_code=500, detail="Create user error")


@godot_router.post("/api/godot/{game_id}/players/login")
@limiter.limit("5/minute")
def login_game_player(request: Request, game_id: int, payload: PlayerAuthPayload, x_api_key: str = Header(...), db: Connection = Depends(get_db)):
    """
    Player login from within the game. Returns a JWT token.
    """
    try:
        with db.cursor() as cursor:
            # Api key verification
            cursor.execute("SELECT id FROM games WHERE api_key = %s AND id = %s;", (x_api_key, game_id))
            game = cursor.fetchone()
            if not game:
                raise HTTPException(status_code=401, detail="Invalid API Key or Game ID.")
                
            # Download player for specific game
            cursor.execute(
                "SELECT id, username, password_hash FROM players WHERE game_id = %s AND username = %s;",
                (game_id, payload.username)
            )
            player = cursor.fetchone()
            
            # Password check
            if not player or not bcrypt.checkpw(payload.password.encode('utf-8'), player['password_hash'].encode('utf-8')):
                raise HTTPException(status_code=401, detail="Invalid username or password.")
                
            # JWT generate
            player_token = create_player_access_token(
                player_id=player['id'], 
                game_id=game_id, 
                username=player['username']
            )

            # Update last login in db
            cursor.execute(
                """
                UPDATE players
                SET last_login=%s
                WHERE game_id = %s AND username = %s;
                """,
                (datetime.now(),game_id, payload.username)
            )

            db.commit()

            return {
                "player_token": player_token,
                "username": player['username'],
                "token_type": "bearer"
            }
    except HTTPException:
        raise
    except Exception as e:
        db.rollback()
        l.error(f"login user error {e}")
        raise HTTPException(status_code=500, detail="Login user error")